// Comprehensive list of major global stocks for autocomplete
// Suffixes adapted for Yahoo Finance compatibility
// Expanded to include broader indices (sWIG80, broad European/US markets)

interface Ticker {
    symbol: string;
    name: string;
    region: string;
}

const createTicker = (symbol: string, name: string, region: string): Ticker => ({ symbol, name, region });

export const POPULAR_TICKERS: Ticker[] = [
    // --- INDICES (Trackable via Yahoo Finance usually with ^ or ETFs) ---
    createTicker('^GSPC', 'S&P 500 Index', 'INDEX'),
    createTicker('^IXIC', 'Nasdaq Composite', 'INDEX'),
    createTicker('^DJI', 'Dow Jones Industrial Average', 'INDEX'),
    createTicker('^WIG20', 'WIG20 Index', 'INDEX'),
    createTicker('^mWIG40', 'mWIG40 Index', 'INDEX'),
    createTicker('^sWIG80', 'sWIG80 Index', 'INDEX'),

    // --- POLAND (GPW - WIG20, mWIG40, sWIG80, NewConnect favorites) ---
    createTicker('CDR.WA', 'CD Projekt RED', 'PL'),
    createTicker('PKO.WA', 'PKO Bank Polski', 'PL'),
    createTicker('PKN.WA', 'Orlen', 'PL'),
    createTicker('PZU.WA', 'PZU', 'PL'),
    createTicker('PEO.WA', 'Bank Pekao', 'PL'),
    createTicker('DNP.WA', 'Dino Polska', 'PL'),
    createTicker('LPP.WA', 'LPP', 'PL'),
    createTicker('KGH.WA', 'KGHM Polska Miedź', 'PL'),
    createTicker('ALE.WA', 'Allegro', 'PL'),
    createTicker('SPL.WA', 'Santander Bank Polska', 'PL'),
    createTicker('PGE.WA', 'PGE', 'PL'),
    createTicker('TPE.WA', 'Tauron', 'PL'),
    createTicker('OPL.WA', 'Orange Polska', 'PL'),
    createTicker('CPS.WA', 'Cyfrowy Polsat', 'PL'),
    createTicker('ALR.WA', 'Alior Bank', 'PL'),
    createTicker('KTY.WA', 'Grupa Kęty', 'PL'),
    createTicker('JSW.WA', 'Jastrzębska Spółka Węglowa', 'PL'),
    createTicker('KRU.WA', 'Kruk', 'PL'),
    createTicker('ACP.WA', 'Asseco Poland', 'PL'),
    createTicker('MBK.WA', 'mBank', 'PL'),
    createTicker('XTB.WA', 'XTB', 'PL'),
    createTicker('11B.WA', '11 bit studios', 'PL'),
    createTicker('BDX.WA', 'Budimex', 'PL'),
    createTicker('CIG.WA', 'CI Games', 'PL'),
    createTicker('TEN.WA', 'Ten Square Games', 'PL'),
    createTicker('LWB.WA', 'Bogdanka', 'PL'),
    createTicker('ENA.WA', 'Enea', 'PL'),
    createTicker('MIL.WA', 'Bank Millennium', 'PL'),
    createTicker('ING.WA', 'ING Bank Śląski', 'PL'),
    createTicker('HUG.WA', 'Huuuge Games', 'PL'),
    createTicker('PLW.WA', 'PlayWay', 'PL'),
    createTicker('BML.WA', 'Biomed Lublin', 'PL'),
    createTicker('MRC.WA', 'Mercator Medical', 'PL'),
    createTicker('APR.WA', 'Auto Partner', 'PL'),
    createTicker('ATT.WA', 'Grupa Azoty', 'PL'),
    createTicker('COG.WA', 'Cognor', 'PL'),
    createTicker('GEA.WA', 'GreenX Metals', 'PL'),
    createTicker('GPW.WA', 'Giełda Papierów Wartościowych', 'PL'),
    createTicker('WPL.WA', 'Wirtualna Polska', 'PL'),
    createTicker('TXT.WA', 'Text (LiveChat)', 'PL'),
    createTicker('CMR.WA', 'Comarch', 'PL'),
    createTicker('DAT.WA', 'DataWalk', 'PL'),
    createTicker('SNT.WA', 'Synektik', 'PL'),
    createTicker('TOR.WA', 'Torpol', 'PL'),
    createTicker('MAB.WA', 'Mabion', 'PL'),
    createTicker('VGO.WA', 'Vigo Photonics', 'PL'),
    createTicker('BETAW20.WA', 'Beta ETF WIG20', 'PL'),
    createTicker('BETAM40.WA', 'Beta ETF mWIG40', 'PL'),
    createTicker('BETAS80.WA', 'Beta ETF sWIG80', 'PL'),
    createTicker('BETAW20LV.WA', 'Beta ETF WIG20lev', 'PL'),
    createTicker('BETAW20ST.WA', 'Beta ETF WIG20short', 'PL'),
    createTicker('ETFW20L.WA', 'Lyxor WIG20 ETF', 'PL'),
    createTicker('STF.WA', 'Stalexport Autostrady', 'PL'),
    createTicker('RBW.WA', 'Rainbow Tours', 'PL'),
    createTicker('SHO.WA', 'Shoper', 'PL'),
    createTicker('MCI.WA', 'MCI Capital', 'PL'),
    createTicker('OAT.WA', 'Mo-BRUK', 'PL'),
    createTicker('ZEP.WA', 'ZE PAK', 'PL'),
    createTicker('BHW.WA', 'Bank Handlowy', 'PL'),

    // --- USA (Expanded Top 100+) ---
    createTicker('AAPL', 'Apple Inc.', 'USA'),
    createTicker('MSFT', 'Microsoft Corporation', 'USA'),
    createTicker('NVDA', 'NVIDIA Corporation', 'USA'),
    createTicker('GOOGL', 'Alphabet Inc. (Class A)', 'USA'),
    createTicker('GOOG', 'Alphabet Inc. (Class C)', 'USA'),
    createTicker('AMZN', 'Amazon.com Inc.', 'USA'),
    createTicker('META', 'Meta Platforms Inc.', 'USA'),
    createTicker('TSLA', 'Tesla Inc.', 'USA'),
    createTicker('BRK.B', 'Berkshire Hathaway', 'USA'),
    createTicker('LLY', 'Eli Lilly and Company', 'USA'),
    createTicker('AVGO', 'Broadcom Inc.', 'USA'),
    createTicker('V', 'Visa Inc.', 'USA'),
    createTicker('JPM', 'JPMorgan Chase', 'USA'),
    createTicker('WMT', 'Walmart Inc.', 'USA'),
    createTicker('XOM', 'Exxon Mobil', 'USA'),
    createTicker('MA', 'Mastercard', 'USA'),
    createTicker('PG', 'Procter & Gamble', 'USA'),
    createTicker('COST', 'Costco Wholesale', 'USA'),
    createTicker('JNJ', 'Johnson & Johnson', 'USA'),
    createTicker('HD', 'Home Depot', 'USA'),
    createTicker('MRK', 'Merck & Co.', 'USA'),
    createTicker('ABBV', 'AbbVie Inc.', 'USA'),
    createTicker('KO', 'Coca-Cola Company', 'USA'),
    createTicker('PEP', 'PepsiCo', 'USA'),
    createTicker('AMD', 'Advanced Micro Devices', 'USA'),
    createTicker('NFLX', 'Netflix Inc.', 'USA'),
    createTicker('INTC', 'Intel Corporation', 'USA'),
    createTicker('DIS', 'Walt Disney Company', 'USA'),
    createTicker('ADBE', 'Adobe Inc.', 'USA'),
    createTicker('CRM', 'Salesforce', 'USA'),
    createTicker('QCOM', 'Qualcomm', 'USA'),
    createTicker('TXN', 'Texas Instruments', 'USA'),
    createTicker('AMAT', 'Applied Materials', 'USA'),
    createTicker('NKE', 'Nike', 'USA'),
    createTicker('SBUX', 'Starbucks', 'USA'),
    createTicker('PLTR', 'Palantir Technologies', 'USA'),
    createTicker('GME', 'GameStop Corp.', 'USA'),
    createTicker('COIN', 'Coinbase Global', 'USA'),
    createTicker('HOOD', 'Robinhood Markets', 'USA'),
    createTicker('UBER', 'Uber Technologies', 'USA'),
    createTicker('ABNB', 'Airbnb', 'USA'),
    createTicker('DASH', 'DoorDash', 'USA'),
    createTicker('SQ', 'Block (Square)', 'USA'),
    createTicker('PYPL', 'PayPal', 'USA'),
    createTicker('SHOP', 'Shopify', 'USA'),
    createTicker('SNOW', 'Snowflake', 'USA'),
    createTicker('ZM', 'Zoom Video', 'USA'),
    createTicker('RBLX', 'Roblox', 'USA'),
    createTicker('U', 'Unity Software', 'USA'),
    createTicker('DKNG', 'DraftKings', 'USA'),
    createTicker('BA', 'Boeing', 'USA'),
    createTicker('RTX', 'RTX Corporation', 'USA'),
    createTicker('LMT', 'Lockheed Martin', 'USA'),
    createTicker('CAT', 'Caterpillar', 'USA'),
    createTicker('DE', 'John Deere', 'USA'),
    createTicker('F', 'Ford Motor', 'USA'),
    createTicker('GM', 'General Motors', 'USA'),
    createTicker('TM', 'Toyota Motor (ADR)', 'USA'),
    createTicker('HMC', 'Honda Motor (ADR)', 'USA'),
    createTicker('SONY', 'Sony Group (ADR)', 'USA'),
    createTicker('T', 'AT&T', 'USA'),
    createTicker('VZ', 'Verizon', 'USA'),
    createTicker('PFE', 'Pfizer', 'USA'),
    createTicker('MRNA', 'Moderna', 'USA'),
    createTicker('ARM', 'Arm Holdings', 'USA'),
    createTicker('TSM', 'Taiwan Semiconductor', 'USA'),
    createTicker('ASML', 'ASML Holding', 'USA'),
    createTicker('ORCL', 'Oracle Corporation', 'USA'),
    createTicker('CSCO', 'Cisco Systems', 'USA'),
    createTicker('IBM', 'IBM', 'USA'),
    createTicker('MU', 'Micron Technology', 'USA'),
    createTicker('NOW', 'ServiceNow', 'USA'),
    createTicker('PANW', 'Palo Alto Networks', 'USA'),
    createTicker('BTC-USD', 'Bitcoin USD', 'CRYPTO'),
    createTicker('ETH-USD', 'Ethereum USD', 'CRYPTO'),

    // --- FRANCE (CAC 40 + Others) ---
    createTicker('MC.PA', 'LVMH Moët Hennessy', 'FR'),
    createTicker('OR.PA', "L'Oréal", 'FR'),
    createTicker('RMS.PA', 'Hermès International', 'FR'),
    createTicker('TTE.PA', 'TotalEnergies', 'FR'),
    createTicker('SAN.PA', 'Sanofi', 'FR'),
    createTicker('AIR.PA', 'Airbus', 'FR'),
    createTicker('SU.PA', 'Schneider Electric', 'FR'),
    createTicker('AI.PA', 'Air Liquide', 'FR'),
    createTicker('EL.PA', 'EssilorLuxottica', 'FR'),
    createTicker('BNP.PA', 'BNP Paribas', 'FR'),
    createTicker('CS.PA', 'AXA', 'FR'),
    createTicker('KER.PA', 'Kering', 'FR'),
    createTicker('DG.PA', 'Vinci', 'FR'),
    createTicker('SAF.PA', 'Safran', 'FR'),
    createTicker('CAP.PA', 'Capgemini', 'FR'),
    createTicker('RNO.PA', 'Renault', 'FR'),
    createTicker('GLE.PA', 'Société Générale', 'FR'),
    createTicker('ACA.PA', 'Crédit Agricole', 'FR'),
    createTicker('ORA.PA', 'Orange', 'FR'),
    createTicker('EN.PA', 'Bouygues', 'FR'),
    createTicker('VIV.PA', 'Vivendi', 'FR'),
    createTicker('ETL.PA', 'Eutelsat', 'FR'),

    // --- GERMANY (DAX 40+) ---
    createTicker('SAP.DE', 'SAP SE', 'DE'),
    createTicker('SIE.DE', 'Siemens AG', 'DE'),
    createTicker('ALV.DE', 'Allianz SE', 'DE'),
    createTicker('DTE.DE', 'Deutsche Telekom', 'DE'),
    createTicker('AIR.DE', 'Airbus SE', 'DE'),
    createTicker('BMW.DE', 'BMW AG', 'DE'),
    createTicker('VOW3.DE', 'Volkswagen AG', 'DE'),
    createTicker('MBG.DE', 'Mercedes-Benz Group', 'DE'),
    createTicker('BAS.DE', 'BASF SE', 'DE'),
    createTicker('BAYN.DE', 'Bayer AG', 'DE'),
    createTicker('MUV2.DE', 'Munich Re', 'DE'),
    createTicker('IFX.DE', 'Infineon Technologies', 'DE'),
    createTicker('DHL.DE', 'DHL Group', 'DE'),
    createTicker('ADS.DE', 'Adidas', 'DE'),
    createTicker('DB1.DE', 'Deutsche Börse', 'DE'),
    createTicker('DBK.DE', 'Deutsche Bank', 'DE'),
    createTicker('EOAN.DE', 'E.ON', 'DE'),
    createTicker('RWE.DE', 'RWE AG', 'DE'),
    createTicker('PUM.DE', 'Puma SE', 'DE'),
    createTicker('CON.DE', 'Continental AG', 'DE'),
    createTicker('HEN3.DE', 'Henkel', 'DE'),
    createTicker('ZAL.DE', 'Zalando', 'DE'),

    // --- UK (FTSE 100) ---
    createTicker('AZN.L', 'AstraZeneca', 'UK'),
    createTicker('SHEL.L', 'Shell plc', 'UK'),
    createTicker('HSBA.L', 'HSBC Holdings', 'UK'),
    createTicker('ULVR.L', 'Unilever', 'UK'),
    createTicker('BP.L', 'BP plc', 'UK'),
    createTicker('DGE.L', 'Diageo', 'UK'),
    createTicker('RIO.L', 'Rio Tinto', 'UK'),
    createTicker('GSK.L', 'GSK plc', 'UK'),
    createTicker('BATS.L', 'British American Tobacco', 'UK'),
    createTicker('GLEN.L', 'Glencore', 'UK'),
    createTicker('REL.L', 'RELX', 'UK'),
    createTicker('LSEG.L', 'London Stock Exchange', 'UK'),
    createTicker('VOD.L', 'Vodafone Group', 'UK'),
    createTicker('BARC.L', 'Barclays', 'UK'),
    createTicker('RR.L', 'Rolls-Royce Holdings', 'UK'),
    createTicker('TSCO.L', 'Tesco', 'UK'),
    createTicker('LLOY.L', 'Lloyds Banking Group', 'UK'),
    createTicker('NWG.L', 'NatWest Group', 'UK'),
    createTicker('NG.L', 'National Grid', 'UK'),

    // --- JAPAN (Nikkei 225 Major) ---
    createTicker('7203.T', 'Toyota Motor', 'JP'),
    createTicker('6758.T', 'Sony Group', 'JP'),
    createTicker('9983.T', 'Fast Retailing (Uniqlo)', 'JP'),
    createTicker('8035.T', 'Tokyo Electron', 'JP'),
    createTicker('9984.T', 'SoftBank Group', 'JP'),
    createTicker('6861.T', 'Keyence', 'JP'),
    createTicker('6098.T', 'Recruit Holdings', 'JP'),
    createTicker('9432.T', 'Nippon Telegraph and Tel', 'JP'),
    createTicker('4063.T', 'Shin-Etsu Chemical', 'JP'),
    createTicker('7267.T', 'Honda Motor', 'JP'),
    createTicker('8306.T', 'Mitsubishi UFJ', 'JP'),
    createTicker('7974.T', 'Nintendo', 'JP'),
    createTicker('6501.T', 'Hitachi', 'JP'),

    // --- GLOBAL ETFs (UCITS & US) ---
    createTicker('SPY', 'SPDR S&P 500 ETF', 'US ETF'),
    createTicker('QQQ', 'Invesco QQQ Trust', 'US ETF'),
    createTicker('IWM', 'iShares Russell 2000', 'US ETF'),
    createTicker('VTI', 'Vanguard Total Stock Mkt', 'US ETF'),
    createTicker('VWCE.DE', 'Vanguard FTSE All-World', 'UCITS ETF'),
    createTicker('EUNL.DE', 'iShares Core MSCI World', 'UCITS ETF'),
    createTicker('IS3N.DE', 'iShares Core MSCI EM IMI', 'UCITS ETF'),
    createTicker('SXR8.DE', 'iShares Core S&P 500', 'UCITS ETF'),
    createTicker('QDVE.DE', 'iShares S&P 500 IT Sector', 'UCITS ETF'),
    createTicker('VUSA.L', 'Vanguard S&P 500 UCITS', 'UCITS ETF'),
    createTicker('CSPX.L', 'iShares Core S&P 500', 'UCITS ETF')
];

export const searchTickers = (query: string): Ticker[] => {
    if (!query) return [];
    const q = query.toUpperCase();

    // Improved search: Priority exact match, then startsWith, then includes
    return POPULAR_TICKERS.filter(t => t.symbol.includes(q) || t.name.toUpperCase().includes(q))
        .sort((a, b) => {
            // Sort logic: Exact startsWith symbol gets priority
            const aStarts = a.symbol.startsWith(q);
            const bStarts = b.symbol.startsWith(q);

            // Exact match bubble to top
            if (a.symbol === q && b.symbol !== q) return -1;
            if (b.symbol === q && a.symbol !== q) return 1;

            if (aStarts && !bStarts) return -1;
            if (!aStarts && bStarts) return 1;
            return 0;
        })
        .slice(0, 15); // Increased limit slightly
};
